version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: focusvault-postgres
    environment:
      POSTGRES_DB: focusvault
      POSTGRES_USER: focusvault_user
      POSTGRES_PASSWORD: focusvault_pass
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: